### ISSUE TITLE
Variables don't work across editors

### ISSUE THREAD

**Issue by wip-abramson** [WebOfTrustInfo/satyrn#12]
Do we want them to?

Not sure how we get to this point.

**Comment by jandrieu** [comment]
We do. I thought this was going to be "free". Are we instantiating a new instance every time we eval?

**Comment by ewelton** [comment]
I did not implement the process isolation - wanted to wait until we had some more structural maturity before i fired off little, uh, 'servers' ;) in the background....

right now it is just lazy-eval, if they are not working that is worthy of some investigation.

**Comment by jandrieu** [comment]
Can we do this as web workers?

That would help with future ideas of a web version.

**Comment by jandrieu** [comment]
There is an interesting problem here we haven't discussed.

Thinking through the eval / repl situation. 

First: YES, I want the API to be, in effect, a simple REPL to the execution context. The code should be run in the "shared" execution context, with console.log directed to the associated console div. I don't want to "automagically" maintain connectivity to long running services. 

[We will need to work through how to pass appropriate console targets so long-running asynchronous javascript methods can run, but I see that as ONLY maintaining the console & error output, NOT automatically doing any other IPC kinds of things. See New Issue https://github.com/WebOfTrustInfo/satyrn/issues/23]

However, we have a bigger problem.

How do we clear out the context from a bad set of code?

We must assume students are going to be capable of writing the most damaging crap, including destroying functions like console.log. Or throwing exceptions.

Because we want to preserve variables across blocks, that means we ALSO need to handle when code from a previous block messes things up for a later block.

I think what we need is a way to rerun the current blocks, up to and including the current one, in a fresh new context.

My assumption is that the code in each block is designed to be run in order and that students, and teachers, will be gradually building up a the context as an ongoing pedagogical framework. That is, the sections build on each other, INCLUDING in the computational context.

This suggests two potential features associated with each code block.
1. A checkbox for "Include in shared context" that is checked by default.
2. A checkbox for "reload shared context on run" which is not checked by default

This might be the easiest way to allow users to manage the context without trying to actually prevent bad code. The bad code is going to happen. The question is what's the best way, in the context of learning a chunk of javascript to let users manage what code is run as part of their sandbox/workbook interactions.

Maybe there are better terms, but it seems like the right functionality for what we need without trying to solve too much.

My only remaining question is what *do* we do when code throws an exception? I added a new issue, because right now we don't handle it well. #25

**Comment by ewelton** [comment]
I like this idea.

This idea + the Bad code + variable sharing in context will all come
together when we move to managing a subprocess per notebook.  I'll take
on that refactoring - i've been waiting to do that until we hit a
critical mass in thinking about the issue, and I think we have a good
MVP landing spot - and one that doesn't require that we re-invent the
kernel model.

A drawback from the kernel model, based on zmq, is that the zmq
libraries are built by gyp on a per-platform basis.  I've done that
before, w/ electron - compiling a per-platform python distribution and
distributing the whole python runtime inside of the electron app - and
you really want a stable distribution/build pathway for that.  It is one
of those threshold things - compiling one non-node standard library is
80% of the effort, expanding that to compiling a huge infrastructure is
relatively simple, once you've made it over the first hurdle.  If you
can gyp one library, you can gyp dozens of libraries - whereas, if you
don't have a single gyp compiled library, then you can skip all of that
headache.

Likewise, there is nothing magic about zmq for the IPC - but again, we
don't want to spend much energy developing a custom-IPC channel. 
forking the child process and using the child_process node libraries
gives us an event driven wrapper around stdin/out/err channels out of
the box.  However, the next step we have to take if we want to have code
blocks linked to output channels is to define a message structure - so
that the kernel process reports "output for block X" and "output for
block Y", and "request evaluation for block Z" followed by "here is
output for block Z".... it is not a complex message structure, but it
is, nevertheless, a messaging layer.

Also - we get into the question of using console.log output at all -
because, if we have multiple concurrent code blocks using console.log,
then there is no way to demux them.  If we want to allow console.log
*and* concurrent, long running execution, we need to have a code-block
linearization around it - so that we can trap/untrap the console.log
output - *or* we provide a hook to be used in lieu of console.log that
can be "passed in" to the running context - and say, use "satyrn.log"
instead of "console.log", which lets us provide each code block with an
"Instance" that knows how to correctly target the output.  There might
be a way to do that using console directly, from the messaging-layer
driver - but again, this is well beyond MVP territory.

As I see it right now, the key is to

a) set up a separate node engine using using node's child_process

b) linearize execution so that we 'completely run a block' - this allows
us to trap stdout/stderr and route it to the appropriate output.

c) support the ability to "restart and rerun previous code blocks up to
this point"

d) setTimeout and other non-functional style evaluation should not be
supported until we take the next step towards building an interactive
computing environment.

I think that would be a good MVP point.

**Comment by jandrieu** [comment]
Looks good.
